'use strict';
/*
 * Utility functions
 */

/**
 * Channels all notifications from the source observable to the given subject.
 *
 * @param {Rx.Observable} source the origin observable
 * @param {Rx.Subject} subject the destination subject
 * @return {Rx.Disposable} a disposable generated by a subscribe method
 */
function channel(source, subject) {
  if (typeof source === 'undefined') {
    throw new Error('Cannot channel() if source is undefined.');
  }
  return source.subscribe(
    function channelNext(x) {
      subject.onNext(x);
    },
    function channelError(err) {
      console.error(err);
    }
  );
}

module.exports = channel;
